version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pizzaria-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SenhaForte@123"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "pidof sqlservr"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: pizzaria-api
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Server=sqlserver,1433;Database=PizzariaDb;User Id=sa;Password=SenhaForte@123;TrustServerCertificate=True"
    ports:
      - "5000:8080"

volumes:
  sql_data:
